config/routes.rb
Rails.application.routes.draw do
  get 'pages/home'
  get 'pages/about'
  resources :articles

  root to: 'pages#home'

  get "signup", to: "users#new"
  resources :users, expect: [:new]

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources 'categories', except: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :article_categories
  has_many :categories, through: :article_categories
  validates :title, presence: true
  validates :description, presence: true
end

app/models/article_category.rb
class ArticleCategory < ApplicationRecord
  belongs_to :article
  belongs_to :category
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :article_categories
  has_many :articles, through: :article_categories
  validates :name, presence: true, uniqueness: true, length: {maximum: 25, minimum: 3}
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase}
  has_many :articles, dependent: :destroy
  validates :username, presence: true,
                       uniqueness: { case_sensitive: false},
                       length: { minimum: 3,maximum: 25 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :email, presence: true,
                    uniqueness: { case_sensitive: false},
                    length: { maximum: 105 },
                    format: {with:  VALID_EMAIL_REGEX }

has_secure_password

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  helper_method :current_user, :logged_in?
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
    #if @current_user is present it prevents the code from hitting the database making the code more efficient
  end

  def logged_in?
    !!current_user
    #turning current_user value to boolean
  end

  def require_user
    if !logged_in?
      flash[:notice] = "you must be logged in to perform that action"
      redirect_to login_path
    end
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :require_user, except: [:show, :index]
  before_action :require_same_user, only: [:edit, :destroy]

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.paginate(page: params[:page], per_page: 2)

  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
    @current_user = User.find(session[:user_id])
  end

  # GET /articles/1/edit
  def edit

  end

  # POST /articles
  # POST /articles.json
  def create
    puts @article, '----------'
    puts @current_user, "___________"
    @article = Article.new(article_params)
    @article.user = current_user
    respond_to do |format|
      if !@article.save
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      else
        format.html { redirect_to articles_url, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def article_params
      params.require(:article).permit(:title, :description, category_ids: [])
    end

    def require_same_user
      if current_user != @article.user
        flash[:alert] = "You can only Edit or Delete your own acticles"
        redirect_to @article
      end
    end
end

app/controllers/categories_controller.rb
 class CategoriesController < ApplicationController
  before_action :require_admin, except: [:index, :show]

  def new
    @category = Category.new
  end

  def index
    @categories = Category.paginate(page: params[:page], per_page: 5)
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:notice] = "Category was successfully created"
      redirect_to @category
    else
      render 'new'
    end
  end

  def show
    @category = Category.find(params[:id])
    @articles = @category.articles.paginate(page: params[:page], per_page: 2)
  end

  private
  def category_params
    params.require(:category).permit(:name)
  end

  def require_admin
    if !(logged_in?)
      flash[:alert] = "Only admins can perform that action"
      redirect_to categories_path
    end
  end
 end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    redirect_to articles_path if logged_in?
  end

  def about
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new

  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:alert] = "Logged in successful"
      redirect_to user
    else
      flash.now[:alert] = "Something went wrong..."
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "loged out..."
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :require_user, only: [:edit, :update, :destroy]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def show
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "sign in successful"
      redirect_to articles_path
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "Your accoutn has been succesfully updated!"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
     @user.destroy
     session[:user_id] = nil if @user == current_user
     flash[:notice] = "Profile and all associated Articles Deleted"
     redirect_to users_path
  end

  private
    def user_params
      params.require(:user).permit(:username, :email, :password)
    end

    def set_user
      @user  = User.find(params[:id])
    end

    def require_same_user
      if current_user != @user && !current_user.admin?
        flash[:alert] = "You can only Edit or Delete your own Profile"
        redirect_to @user
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def gravatar_for(user, options = { size: 80})
    email_address = user.email.downcase
    hash = Digest::MD5.hexdigest(email_address)
    size = options[:size]
    gravatar_url = "https://www.gravatar.com/avatar/#{hash}?s=#{size}"
    image_tag(gravatar_url, alt: user.username, class: "rounded shadow mx-auto d-block")
  end

end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_article.html.erb
<div class="container">
  <% articles.each do |article| %>
  <div class="row justify-content-md-center">
    <div class="col-8 mt-4">
      <div class="card text-center shadow mb-5 bg-white rounded">
        <div class="card-header font-italic">
        <% if article.user %>
            by <%= link_to article.user.username, user_path(article.user) %>
        <% end %>
        <% if article.categories.any? %>
          <div class="mt-2">
            <%= render article.categories %>
          </div>
        <% end %>
        </div>
        <div class="card-body">
          <h5 class="card-title"><%= link_to article.title, article_path(article), class: "text-success"%></h5>
          <p class="card-text"><%= truncate(article.description, length: 100) %></p>
          <%= link_to 'Show', article , class: "btn btn-outline-success"%>
          <% if logged_in? && (article.user === current_user || current_user.admin?)%>
            <%= link_to 'Edit', edit_article_path(article), class: "btn btn-outline-info" %>
            <%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-outline-danger" %>
          <% end %>
        </div>
        <div class="card-footer text-muted">
          <small> Created <%= time_ago_in_words(article.created_at) %> ago, Updated <%= time_ago_in_words(article.updated_at)%></small>
        </div>
      </div>
    </div>
  </div>
  <% end %>
</div>

app/views/articles/_form.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-10">
      <%= form_with(model: article, class: "shadow p-3 mb-3 bg-secondary rounded", local: true) do |form| %>

        <%= render "shared/errors", obj: @article %>

        <div class="form-group row">
          <%= form.label :title, class: "col-2 col-form-label text-light"%>
          <div class="col-10 shadow rounded">
            <%= form.text_field :title, class:"form-control", placeholder: "Title of the article"%>
          </div>
        </div>

        <div class="form-group row">
          <%= form.label :description, class: "col-2 col-form-label text-light" %>
          <div class="col-10 shadow rounded">
            <%= form.text_area :description, rows: 10, class: "form-control", placeholder: "Description of the article"%>
          </div>
        </div>

        <div class="form-group row">
          <%= form.label :category, class: "col-2 col-form-label text-light" %>
          <div class="col-10 shadow rounded">
          <%= form.collection_select(:category_ids, Category.all, :id, :name, {prompt: "Please select categories(Can be empty)"}, {multiple: true, class: "custom-select shadow roundedl"}) %>
          </div>
        </div>

        <div class="form-group row justify-content-center">
          <%= form.submit class: "btn btn-outline-light btn-lg"%>
        </div>
      <% end %>
    </div>

    <div class="mb-3">
      <%= link_to '[ Cancel and return to Articles Listing ]', articles_path %>
    </div>
  </div>
</div>

app/views/articles/edit.html.erb
<h1 class="text-center mt-4" >Create New Article</h1>
<%= render 'form', article: @article %>

app/views/articles/index.html.erb
<h1 class="text-center mt-4" >Articles</h1>

<div class="apple_pagination">
    <div class="page_info">
      <%= page_entries_info @articles %>
    </div>
    <%= will_paginate @posts, :container => false %>
  </div>


<%= render "article", articles: @articles%>

<div class="apple_pagination">
    <div class="page_info">
      <%= page_entries_info @articles %>
    </div>
    <%= will_paginate @posts, :container => false %>
  </div>

app/views/articles/new.html.erb
<h1 class="text-center mt-4" >Create New Article</h1>
<%= render 'form', article: @article %>

app/views/articles/show.html.erb
<div class="row justify-content-md-center">
  <div class="col-8 mt-4">
    <div class="card text-center shadow mb-5 bg-white rounded">
      <div class="card-header font-italic">
        by <%= @article.user.username if @article.user%>
        <%= link_to gravatar_for(@article.user), user_path(@article.user) %>
        <% if @article.categories.any? %>
          <div class="mt-2">
            <%= render @article.categories %>
          </div>
        <% end %>
      </div>
      <div class="card-body">
        <h5 class="card-title text-success"><%= @article.title%></h5>
        <div class="card-text"><%= simple_format(@article.description) %></div>
        <% if logged_in? && @article.user === current_user %>
          <%= link_to 'Edit', edit_article_path(@article), class: "btn btn-outline-info" %>
          <%= link_to 'Destroy', @article, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-outline-danger" %>
        <% end %>
      </div>
      <div class="card-footer text-muted">
        <small> Created <%= time_ago_in_words(@article.created_at) %> ago, Updated <%= time_ago_in_words(@article.updated_at)%></small>
      </div>
    </div>
  </div>
</div>

app/views/categories/_categories.html.erb
<div>
  <div class="apple_pagination">
    <%= will_paginate @categories, :container => false %>
  </div>

  <div class="container">
    <% @categories.each do |category| %>
    <div class="row justify-content-md-center">
      <div class="col-4 mt-4">
        <div class="card text-center shadow mb-5 bg-white rounded">

          <div class="card-body">
            <h5 class="card-title"><%= link_to category.name, category_path(category), class: "text-success"%></h5>
            <p class="card-text"><%= pluralize(category.articles.count, "article") %></p>
          </div>
          <div class="card-footer text-muted">
            <small> Created <%= time_ago_in_words(category.created_at) %> ago, Updated <%= time_ago_in_words(category.updated_at)%></small>
          </div>
        </div>
      </div>
    </div>
    <% end %>
  </div>

  <div class="apple_pagination">
    <%= will_paginate @categories, :container => false %>
  </div>
</div>

app/views/categories/_category.html.erb
<%= link_to category.name , category_path(category), class: "badge badge-pill mr-1 badge-info"%>

app/views/categories/_form.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-10">
      <%= form_with(model: @category, class: "shadow p-3 mb-3 bg-secondary rounded", local: true) do |form| %>

      <%= render "shared/errors", obj: @category %>

        <div class="form-group row">
          <%= form.label :name , "Category name",  class: "col-2 col-form-label text-light"%>
          <div class="col-10 shadow rounded">
            <%= form.text_field :name, class:"form-control", placeholder: "Name of the Category"%>
          </div>
        </div>

        <div class="form-group row justify-content-center">
          <%= form.submit  class: "btn btn-outline-light btn-lg"%>
        </div>
      <% end %>
    </div>

    <div class="mb-3">
    <% if @category.id %>
        <%= link_to '[ Cancel and return to Category ]', category_path(@category) %>
    <% else %>
        <%= link_to '[ Cancel and return to Categories listing ]', categories_path %>
    <% end %>
    </div>
  </div>
</div>

app/views/categories/edit.html.erb
<h1 class="text-center mt-4" >Update category</h1>
<%= render 'form'%>

app/views/categories/index.html.erb
<h1 class="text-center mt-4" >Listing all categories</h1>

<%= render "categories", categories: @categories%>

app/views/categories/new.html.erb
<h1 class="text-center mt-4" >Create a new category</h1>
<%= render 'form'%>

app/views/categories/show.html.erb
 <h1 class="text-center mt-4">Category: <%= @category.name %></h1>

<% if logged_in? && current_user.admin? %>
  <div class="text-center mt-4">
    <%= link_to "Edit Category Name", edit_category_path(@category), class: "btn btn-outline-info" %>
  </div>
<% end %>

 <h3 class="text-center mt-4">Articles</h3>

 <div class="apple_pagination">
  <%= will_paginate @articles, container: false %>
 </div>

 <%= render "articles/article", articles: @category.articles%>

 <div class="apple_pagination">
  <%= will_paginate @articles, container: false %>
 </div>

app/views/layouts/_footer.html.erb
<footer id="sticky-footer" class="py-4 bg-dark text-white">
    <div class="container text-center">
      <small><%= link_to "Varun Kumar S", "mailto: varunkumar0930@gmail.com", class: "text-white"%></small>
    </div>
  </footer>

app/views/layouts/_messages.html.erb
  <% flash.each do |name, msg| %>
    <div class="alert alert-<%= name == "notice" ? "success" : "danger" %> alert-dismissible fade show" role="alert">
      <%= msg %>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  <% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg ">
  <%= link_to "Alpha Blog", root_path, class: "navbar-brand", id: "logo"%>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to "Bloggers", users_path, class: "nav-link" %>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Articles
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <% if logged_in? %>
            <%= link_to "New Article", new_article_path, class: "dropdown-item"%>
          <% end %>
            <%= link_to "View Articles", articles_url, class: "dropdown-item"%>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>

      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Categories
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <% if logged_in? && current_user.admin?%>
            <%= link_to "New Category", new_category_path, class: "dropdown-item"%>
          <% end %>
          <%= link_to "View Categories", categories_path, class: "dropdown-item"%>
        </div>
      </li>

      <%if logged_in?%>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
           <%= "(Admin)" if current_user.admin? %> Profile [<%= current_user.username %>]
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to "View your Profile", user_path(current_user), class: "dropdown-item"%>
            <%= link_to "Edit your profile", edit_user_path(current_user) , class: "dropdown-item"%>
            <%= link_to 'Logout', logout_path, class: "dropdown-item text-danger", method: :delete%>
             <%= link_to 'Delete Account', user_path(current_user), class: "dropdown-item text-danger", method: :delete, data: {confirm: "Are you sure?"}%>
          </div>
      </li>
      <% else %>
        <li class="nav-item">
          <%= link_to 'Login', login_path, class: "nav-link"%>
        </li>
        <li class="nav-item">
          <%= link_to 'Sign up', signup_path, class: "nav-link"%>
        </li>
      <% end %>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

  </head>

  <body class="d-flex flex-column">
    <%= render 'layouts/navigation' %>
    <div id="page-content">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>
    <%= render 'layouts/footer'%>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>

    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </body>
</html>

app/views/pages/about.html.erb
<h1>This is an About page</h1>

 <%= link_to 'Home', pages_home_path %>

app/views/pages/home.html.erb
<div class="container" id="home-container">
  <div class="jumbotron text-center text-white">
    <h1 class="display-4">Alpha Blog</h1>
    <p class="lead">This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
    <hr class="my-4">
    <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
    <%= link_to "Sign up", signup_path, class: "btn btn-success btn-lg" %>
  </div>
</div>

app/views/shared/_errors.html.erb
 <% if obj.errors.any? %>
  <div class="alert alert-danger  alert-dismissible fade show" role="alert">
    <h4 class="alert-heading">The following errors prevented the <%= obj.class.name.downcase%> from being saved.</h4>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <ul>
      <% obj.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/_form.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-10">
      <%= form_with(model: @user, class: "shadow p-3 mb-3 bg-secondary rounded", local: true) do |form| %>

      <%= render "shared/errors", obj: @user %>

        <div class="form-group row">
          <%= form.label :username, class: "col-2 col-form-label text-light"%>
          <div class="col-10 shadow rounded">
            <%= form.text_field :username, class:"form-control", placeholder: "username"%>
          </div>
        </div>

        <div class="form-group row">
          <%= form.label :email, class: "col-2 col-form-label text-light" %>
          <div class="col-10 shadow rounded">
            <%= form.text_area :email, class: "form-control", placeholder: "email"%>
          </div>
        </div>

        <div class="form-group row">
          <%= form.label :password, class: "col-2 col-form-label text-light" %>
          <div class="col-10 shadow rounded">
            <%= form.password_field :password, class: "form-control", placeholder: "password"%>
          </div>
        </div>

        <div class="form-group row justify-content-center">
          <%= form.submit(@user.new_record? ? "Sign up" : "Update profile",  class: "btn btn-outline-light btn-lg")%>
        </div>
      <% end %>
    </div>

    <div class="mb-3">
      <%= link_to '[ Cancel and return to Articles Listing ]', articles_path %>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<h1 class="text-center mt-4" >Signup</h1>
<%= render 'form'%>

app/views/users/index.html.erb
<h1 class="text-center mt-4">Aplha Bolggers</h1>

<div class="container">
  <% @users.each do |user| %>
  <div class="row justify-content-md-center">
    <div class="col-8 mt-4">
      <div class="card text-center shadow mb-5 bg-white rounded">
        <div class="card-header font-italic"><%= link_to user.username, user%>
        </div>
        <div class="card-body">
          <h5 class="card-title">
          <%= link_to gravatar_for(user, size: 150), user%></h5>
          <p class="card-text"><%= pluralize(user.articles.count, "article") %></p>
          <%= link_to 'View profile', user , class: "btn btn-outline-success"%>
          <% if logged_in? %>
            <% if user == current_user %>
              <%= link_to 'Edit profile', edit_user_path(user), class: "btn btn-outline-info" %>
            <% end %>
            <% if current_user.admin? %>
              <%= link_to "Delete User", user_path(user) , class: 'btn btn-outline-danger', method: :delete, data: {confirm: 'Are you sure you want to delete the user?'}%>
            <% end %>
          <% end %>
        </div>
        <div class="card-footer text-muted">
          <small> Joined <%= time_ago_in_words(user.created_at) %> ago</small>
        </div>
      </div>
    </div>
  </div>
  <% end %>
</div>

app/views/users/new.html.erb
<h1 class="text-center mt-4" >Signup</h1>
<%= render 'form'%>

app/views/users/show.html.erb
 <h1 class="text-center mt-4"><%= @user.username %>'s Profile</h1>

 <%= gravatar_for @user, size: 200 %>

<% if logged_in? && @user === current_user %>
  <div class="text-center mt-4">
    <%= link_to "Edit profile", edit_user_path, class: "btn btn-outline-info" %>
  </div>
<% end %>

 <h3 class="text-center mt-4">Articles</h3>

 <%= render "articles/article", articles: @user.articles%>